# src/agent/state.py

from typing import Any, TypedDict


class AgentState(TypedDict, total=False):
    """
    State shared between LangGraph nodes.
    """

    # Original user question
    user_query: str

    # Result from the intent planner
    intent: str

    # Loaded student DataFrame
    dataframe: Any

    # Dataset schema information
    schema: dict[str, Any]

    # FAISS vector store
    vector_store: Any

    # Result generated by the Pandas tool
    pandas_result: Any

    # Documents retrieved by the RAG tool
    rag_result: list[Any]

    # Combined context passed to the response LLM
    context: str

    # Final answer returned to the user
    final_answer: str

    # Error information, if something fails
    error: str