# src/tools/pandas_tool.py

from typing import Any

import pandas as pd

from src.utils.logger import get_logger


logger = get_logger(__name__)


def execute_pandas_query(
    dataframe: pd.DataFrame,
    query: str,
) -> Any:
    """
    Execute a Pandas expression on the provided DataFrame.

    Args:
        dataframe: Student dataset.
        query: Pandas expression generated by the LLM.

    Returns:
        Result of the Pandas operation.
    """

    if dataframe.empty:
        logger.warning("Pandas query received an empty DataFrame.")
        return None

    if not query or not query.strip():
        raise ValueError("Pandas query cannot be empty.")

    logger.info("Executing Pandas query: %s", query)

    try:
        # Restricted namespace for Pandas execution.
        local_namespace = {
            "df": dataframe,
            "pd": pd,
        }

        result = eval(
            query,
            {"__builtins__": {}},
            local_namespace,
        )

        logger.info("Pandas query executed successfully.")

        return result

    except Exception:
        logger.exception(
            "Pandas query execution failed: %s",
            query,
        )
        raise